### ISSUE TITLE
Test results are duplicated

### ISSUE THREAD

**Issue by andrewpdc** [fescobar/allure-docker-service#91]
I use the send_results.py to update the result to allure server. But I found the test result are duplicated not override for some of tests. I have to clean results every time. How can it determine if it's the same test?
![Capture](https://user-images.githubusercontent.com/2361113/84877903-aa414a80-b0bb-11ea-8f3c-863dd8f54342.PNG)

**Comment by fescobar** [comment]
@andrewpdc are you using `generate-report` endpoint?, because remember you have to use `CHECK_RESULTS=NONE`, otherwise, 1 execution is from your request and the next one is because changes were detected automatically. With `NONE` you disable the automatic execution.

**Comment by fescobar** [comment]
You can see who generated the execution here: 
<img width="398" alt="Screen Shot 2020-06-17 at 10 30 32 AM" src="https://user-images.githubusercontent.com/1236418/84881374-a98dc180-b085-11ea-918f-3636d170a6a0.png">

**Comment by andrewpdc** [comment]
@fescobar I use send-results end point. Actually, I manually execute the send_result.py to update. There are four suites. I run the script separately and found there are duplicated tests.

**Comment by fescobar** [comment]
@andrewpdc Please, Can you send me evidence like logs, configuration, commands, screenshots and describe step by steps what are you doing?

**Comment by fescobar** [comment]
@andrewpdc Every execution takes the files from `allure-results`. If you want to avoid clean results, what you can do is using `CHECK_RESULTS=NONE` and after running 4 suites you can use endpoint `GET /generate-report` to get 1 execution including your 4 suites. The automatic execution is commonly used for local executions.

**Comment by andrewpdc** [comment]
@fescobar Thanks. I will try your method. And because we daily update the result, i will collect evidence in next few days. If the issue is reproduced, i will attach the allure json files.

**Comment by fescobar** [comment]
@andrewpdc the best way to identify your problem it's describing step by step like a test case. I will try to describe what you are doing to show you why it is not an issue.

1. You have a configuration like this:
```
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
```
2. You run the first suite of tests
3. You send the files from suite1 using `POST /send-results`. 
4. Those files are detected by the container so as you have Automatic Execution it will generate the report automatically (Execution # 1)
5. You run the second suite of tests
6. Those files are detected by the container, then it generates a second report, but in this case, you have the previous results from suite1. For that reason, you will see like a second execution from suite1 and the first execution from suite2  (Execution # 2).
7. If you clean results, it will be counted as execution(Execution # 3), but you will see zero tests because the container will try to take the files from results which in this case is empty. As a result, you won't see the graphics correctly.

The option `CHECK_RESULTS_EVERY_SECONDS: 1` is to enable automatic execution. For this example every 1 second. This option is to avoid to call the `GET /generate-report` from your side. But for your case, it is not useful.

As I said before, `CHECK_RESULTS_EVERY_SECONDS: NONE` is the best option for you, because once you send all files results you can execute `GET /generate-report` from your own and you will see the graphics correctly.
